### ISSUE TITLE
Tree shaking

### ISSUE THREAD

**Issue by em** [impulse/heroicons-react#11]
You're generating a single build with every icon making it so anyone who wants to use a few icons has to include a 203K dependency.

Don't do that

**Comment by luisrudge** [comment]
@em what would be the solution here? export each individual icon?
I'll send a PR to fix it :tada:

**Comment by em** [comment]
I don't use typescript, I use rescript, so I have to look up best practices for publishing typescript libraries. But surely it's not a single js build file. The build setup being used here is intended for bundling a production site, not a package.

https://stackoverflow.com/questions/37639567/npm-modules-typescript-best-practices
https://stackoverflow.com/questions/30928253/writing-npm-modules-in-typescript
