### ISSUE TITLE
Visual differences compared to Tailwind UI styling

### ISSUE THREAD

**Issue by pikeas** [impulse/heroicons-react#6]
I'm not super familiar with SVG options, but I imagine this is due to the stroke type, the viewbox, etc.

Example for GlobeAlt, top is taken from Tailwind UI, bottom is the `GlobeAlt` component from this library.

<img width="68" alt="Screen Shot 2020-09-08 at 17 21 57" src="https://user-images.githubusercontent.com/686573/92539916-d6babd80-f1f7-11ea-9397-d7018945a9f8.png">

**Comment by ecklf** [comment]
@pikeas which tailwindui component does contain that globe?
Note that there are solid and outlined versions of the icons (I assume tailwindui is using the outlined GlobeAlt)

![image](https://user-images.githubusercontent.com/8146736/92706965-38dd0500-f355-11ea-9705-7a607e0e3f90.png)
Left Solid - Right Outline

**Comment by pikeas** [comment]
https://tailwindui.com/components/marketing/sections/feature-sections

**Comment by ecklf** [comment]
> https://tailwindui.com/components/marketing/sections/feature

Seems like the outlined SVG is used there. I only optimize the source files, give them a default size and bundle them into react components.
